-- Auto-generated: preload strategies from settings.json
-- Generated: 2026-07-17 13:49:02
-- QUIC: 57, DISCORD: 1, History: 153

-- Blocked strategies (default + user-defined)
-- Function slm_is_blocked() is defined in strategy-lock-manager.lua
-- Format: slm_preload_blocked(askey, hostname, {strategies})
slm_preload_blocked("tls", "google.com", {1})
slm_preload_blocked("http", "google.com", {1})
slm_preload_blocked("mtproto", "google.com", {1})
slm_preload_blocked("tls", "facebook.com", {1})
slm_preload_blocked("http", "facebook.com", {1})
slm_preload_blocked("mtproto", "facebook.com", {1})
slm_preload_blocked("tls", "discord.gg", {1})
slm_preload_blocked("http", "discord.gg", {1})
slm_preload_blocked("mtproto", "discord.gg", {1})
slm_preload_blocked("tls", "google.ru", {1})
slm_preload_blocked("http", "google.ru", {1})
slm_preload_blocked("mtproto", "google.ru", {1})
slm_preload_blocked("tls", "whatsapp.net", {1})
slm_preload_blocked("http", "whatsapp.net", {1})
slm_preload_blocked("mtproto", "whatsapp.net", {1})
slm_preload_blocked("tls", "googleadservices.com", {1})
slm_preload_blocked("http", "googleadservices.com", {1})
slm_preload_blocked("mtproto", "googleadservices.com", {1})
slm_preload_blocked("tls", "tiktok.com", {1})
slm_preload_blocked("http", "tiktok.com", {1})
slm_preload_blocked("mtproto", "tiktok.com", {1})
slm_preload_blocked("tls", "twitter.com", {1})
slm_preload_blocked("http", "twitter.com", {1})
slm_preload_blocked("mtproto", "twitter.com", {1})
slm_preload_blocked("tls", "youtube.com", {1})
slm_preload_blocked("http", "youtube.com", {1})
slm_preload_blocked("mtproto", "youtube.com", {1})
slm_preload_blocked("tls", "tiktokcdn.com", {1})
slm_preload_blocked("http", "tiktokcdn.com", {1})
slm_preload_blocked("mtproto", "tiktokcdn.com", {1})
slm_preload_blocked("tls", "netflix.com", {1})
slm_preload_blocked("http", "netflix.com", {1})
slm_preload_blocked("mtproto", "netflix.com", {1})
slm_preload_blocked("tls", "roblox.com", {1})
slm_preload_blocked("http", "roblox.com", {1})
slm_preload_blocked("mtproto", "roblox.com", {1})
slm_preload_blocked("tls", "ytimg.com", {1})
slm_preload_blocked("http", "ytimg.com", {1})
slm_preload_blocked("mtproto", "ytimg.com", {1})
slm_preload_blocked("tls", "redditmedia.com", {1})
slm_preload_blocked("http", "redditmedia.com", {1})
slm_preload_blocked("mtproto", "redditmedia.com", {1})
slm_preload_blocked("tls", "instagram.com", {1})
slm_preload_blocked("http", "instagram.com", {1})
slm_preload_blocked("mtproto", "instagram.com", {1})
slm_preload_blocked("tls", "googlevideo.com", {1})
slm_preload_blocked("http", "googlevideo.com", {1})
slm_preload_blocked("mtproto", "googlevideo.com", {1})
slm_preload_blocked("tls", "ggpht.com", {1})
slm_preload_blocked("http", "ggpht.com", {1})
slm_preload_blocked("mtproto", "ggpht.com", {1})
slm_preload_blocked("tls", "twitch.tv", {1})
slm_preload_blocked("http", "twitch.tv", {1})
slm_preload_blocked("mtproto", "twitch.tv", {1})
slm_preload_blocked("tls", "cdninstagram.com", {1})
slm_preload_blocked("http", "cdninstagram.com", {1})
slm_preload_blocked("mtproto", "cdninstagram.com", {1})
slm_preload_blocked("tls", "reddit.com", {1})
slm_preload_blocked("http", "reddit.com", {1})
slm_preload_blocked("mtproto", "reddit.com", {1})
slm_preload_blocked("tls", "twitchcdn.net", {1})
slm_preload_blocked("http", "twitchcdn.net", {1})
slm_preload_blocked("mtproto", "twitchcdn.net", {1})
slm_preload_blocked("tls", "googleapis.com", {1})
slm_preload_blocked("http", "googleapis.com", {1})
slm_preload_blocked("mtproto", "googleapis.com", {1})
slm_preload_blocked("tls", "x.com", {1})
slm_preload_blocked("http", "x.com", {1})
slm_preload_blocked("mtproto", "x.com", {1})
slm_preload_blocked("tls", "spotify.com", {1})
slm_preload_blocked("http", "spotify.com", {1})
slm_preload_blocked("mtproto", "spotify.com", {1})
slm_preload_blocked("tls", "googletagmanager.com", {1})
slm_preload_blocked("http", "googletagmanager.com", {1})
slm_preload_blocked("mtproto", "googletagmanager.com", {1})
slm_preload_blocked("tls", "steamcommunity.com", {1})
slm_preload_blocked("http", "steamcommunity.com", {1})
slm_preload_blocked("mtproto", "steamcommunity.com", {1})
slm_preload_blocked("tls", "discordapp.com", {1})
slm_preload_blocked("http", "discordapp.com", {1})
slm_preload_blocked("mtproto", "discordapp.com", {1})
slm_preload_blocked("tls", "githubusercontent.com", {1})
slm_preload_blocked("http", "githubusercontent.com", {1})
slm_preload_blocked("mtproto", "githubusercontent.com", {1})
slm_preload_blocked("tls", "withyoutube.com", {1})
slm_preload_blocked("http", "withyoutube.com", {1})
slm_preload_blocked("mtproto", "withyoutube.com", {1})
slm_preload_blocked("tls", "googlesyndication.com", {1})
slm_preload_blocked("http", "googlesyndication.com", {1})
slm_preload_blocked("mtproto", "googlesyndication.com", {1})
slm_preload_blocked("tls", "googleusercontent.com", {1})
slm_preload_blocked("http", "googleusercontent.com", {1})
slm_preload_blocked("mtproto", "googleusercontent.com", {1})
slm_preload_blocked("tls", "discord.com", {1})
slm_preload_blocked("http", "discord.com", {1})
slm_preload_blocked("mtproto", "discord.com", {1})
slm_preload_blocked("tls", "discord.media", {1})
slm_preload_blocked("http", "discord.media", {1})
slm_preload_blocked("mtproto", "discord.media", {1})
slm_preload_blocked("tls", "igcdn.com", {1})
slm_preload_blocked("http", "igcdn.com", {1})
slm_preload_blocked("mtproto", "igcdn.com", {1})
slm_preload_blocked("tls", "steampowered.com", {1})
slm_preload_blocked("http", "steampowered.com", {1})
slm_preload_blocked("mtproto", "steampowered.com", {1})
slm_preload_blocked("tls", "redd.it", {1})
slm_preload_blocked("http", "redd.it", {1})
slm_preload_blocked("mtproto", "redd.it", {1})
slm_preload_blocked("tls", "musical.ly", {1})
slm_preload_blocked("http", "musical.ly", {1})
slm_preload_blocked("mtproto", "musical.ly", {1})
slm_preload_blocked("tls", "whatsapp.com", {1})
slm_preload_blocked("http", "whatsapp.com", {1})
slm_preload_blocked("mtproto", "whatsapp.com", {1})
slm_preload_blocked("tls", "fb.me", {1})
slm_preload_blocked("http", "fb.me", {1})
slm_preload_blocked("mtproto", "fb.me", {1})
slm_preload_blocked("tls", "rutracker.org", {1})
slm_preload_blocked("http", "rutracker.org", {1})
slm_preload_blocked("mtproto", "rutracker.org", {1})
slm_preload_blocked("tls", "youtube-nocookie.com", {1})
slm_preload_blocked("http", "youtube-nocookie.com", {1})
slm_preload_blocked("mtproto", "youtube-nocookie.com", {1})
slm_preload_blocked("tls", "withgoogle.com", {1})
slm_preload_blocked("http", "withgoogle.com", {1})
slm_preload_blocked("mtproto", "withgoogle.com", {1})
slm_preload_blocked("tls", "ig.me", {1})
slm_preload_blocked("http", "ig.me", {1})
slm_preload_blocked("mtproto", "ig.me", {1})
slm_preload_blocked("tls", "youtu.be", {1})
slm_preload_blocked("http", "youtu.be", {1})
slm_preload_blocked("mtproto", "youtu.be", {1})
slm_preload_blocked("tls", "google-analytics.com", {1})
slm_preload_blocked("http", "google-analytics.com", {1})
slm_preload_blocked("mtproto", "google-analytics.com", {1})
slm_preload_blocked("tls", "yt3.ggpht.com", {1})
slm_preload_blocked("http", "yt3.ggpht.com", {1})
slm_preload_blocked("mtproto", "yt3.ggpht.com", {1})
slm_preload_blocked("tls", "dns.google", {1})
slm_preload_blocked("http", "dns.google", {1})
slm_preload_blocked("mtproto", "dns.google", {1})
slm_preload_blocked("tls", "rbxcdn.com", {1})
slm_preload_blocked("http", "rbxcdn.com", {1})
slm_preload_blocked("mtproto", "rbxcdn.com", {1})
slm_preload_blocked("tls", "googleanalytics.com", {1})
slm_preload_blocked("http", "googleanalytics.com", {1})
slm_preload_blocked("mtproto", "googleanalytics.com", {1})
slm_preload_blocked("tls", "nflxvideo.net", {1})
slm_preload_blocked("http", "nflxvideo.net", {1})
slm_preload_blocked("mtproto", "nflxvideo.net", {1})
slm_preload_blocked("tls", "spotifycdn.com", {1})
slm_preload_blocked("http", "spotifycdn.com", {1})
slm_preload_blocked("mtproto", "spotifycdn.com", {1})
slm_preload_blocked("tls", "github.com", {1})
slm_preload_blocked("http", "github.com", {1})
slm_preload_blocked("mtproto", "github.com", {1})
slm_preload_blocked("tls", "steamstatic.com", {1})
slm_preload_blocked("http", "steamstatic.com", {1})
slm_preload_blocked("mtproto", "steamstatic.com", {1})
slm_preload_blocked("tls", "twimg.com", {1})
slm_preload_blocked("http", "twimg.com", {1})
slm_preload_blocked("mtproto", "twimg.com", {1})
slm_preload_blocked("tls", "fbcdn.net", {1})
slm_preload_blocked("http", "fbcdn.net", {1})
slm_preload_blocked("mtproto", "fbcdn.net", {1})
slm_preload_blocked("tls", "gstatic.com", {1})
slm_preload_blocked("http", "gstatic.com", {1})
slm_preload_blocked("mtproto", "gstatic.com", {1})
slm_preload_blocked("tls", "fb.com", {1})
slm_preload_blocked("http", "fb.com", {1})
slm_preload_blocked("mtproto", "fb.com", {1})
slm_preload_blocked("tls", "discordapp.net", {1})
slm_preload_blocked("http", "discordapp.net", {1})
slm_preload_blocked("mtproto", "discordapp.net", {1})
slm_preload_blocked("tls", "doubleclick.net", {1})
slm_preload_blocked("http", "doubleclick.net", {1})
slm_preload_blocked("mtproto", "doubleclick.net", {1})

slm_preload_locked("quic", "[tls] mozilla.cloudflare-dns.com", 3, false)
slm_preload_locked("quic", "[tls] dns.google.com", 3, false)
slm_preload_locked("quic", "[tls] discord.com", 5, false)
slm_preload_locked("quic", "[unknown] discord.com", 2, false)
slm_preload_locked("quic", "[tls] www.youtube.com", 3, false)
slm_preload_locked("quic", "[tls] cdn.discordapp.com", 5, false)
slm_preload_locked("quic", "[tls] gateway.discord.gg", 5, false)
slm_preload_locked("quic", "[tls] rutracker.org", 5, false)
slm_preload_locked("quic", "[tls] events.7tv.io", 11, false)
slm_preload_locked("quic", "[tls] live.bhvrdbd.com", 2, false)
slm_preload_locked("quic", "[tls] osi.office.net", 3, false)
slm_preload_locked("quic", "[tls] svc.cloud.microsoft", 3, false)
slm_preload_locked("quic", "[tls] data.msn.com", 2, false)
slm_preload_locked("quic", "[tls] 7tv.io", 3, false)
slm_preload_locked("quic", "[tls] exp.notion.com", 94, false)
slm_preload_locked("quic", "[tls] chat.twitch.tv", 3, false)
slm_preload_locked("quic", "[tls] us-west-2.amazonaws.com", 2, false)
slm_preload_locked("quic", "[quic] discord.com", 3, false)
slm_preload_locked("quic", "[tls] catalog.gamepass.com", 3, false)
slm_preload_locked("quic", "[unknown] udp 203.23.0.0", 7, false)
slm_preload_locked("quic", "[tls] yastatic.net", 4, false)
slm_preload_locked("quic", "[tls] cloudflare-ech.com", 15, false)
slm_preload_locked("quic", "[tls] c.youtube.com", 2, false)
slm_preload_locked("quic", "[tls] pub-71ebeef63bbd4131a5876b8a44c21c95.r2.dev", 2, false)
slm_preload_locked("quic", "[tls] ntp.msn.com", 3, false)
slm_preload_locked("quic", "[tls] steamcommunity.com", 9, false)
slm_preload_locked("quic", "[quic] nel.cloudflare.com", 2, false)
slm_preload_locked("quic", "[tls] codex.sale", 3, false)
slm_preload_locked("quic", "[tls] github.githubassets.com", 2, false)
slm_preload_locked("quic", "[tls] cdn-banners.exitlag.com", 2, false)
slm_preload_locked("quic", "[tls] gql.twitch.tv", 2, false)
slm_preload_locked("quic", "[quic] chrome.cloudflare-dns.com", 2, false)
slm_preload_locked("quic", "[tls] chrome.cloudflare-dns.com", 31, false)
slm_preload_locked("quic", "[tls] cloudflare-dns.com", 3, false)
slm_preload_locked("quic", "[quic] www.google.com", 2, false)
slm_preload_locked("quic", "[tls] ab.chatgpt.com", 5, false)
slm_preload_locked("quic", "[tls] sfunpay.com", 30, false)
slm_preload_locked("quic", "[tls] dns.comss.one", 66, false)
slm_preload_locked("quic", "[tls] app.notion.com", 122, false)
slm_preload_locked("quic", "[tls] static-cdn.jtvnw.net", 7, false)
slm_preload_locked("quic", "[tls] marketplace.visualstudio.com", 3, false)
slm_preload_locked("quic", "[tls] chatgpt.com", 3, false)
slm_preload_locked("quic", "[tls] nel.cloudflare.com", 12, false)
slm_preload_locked("quic", "[tls] chat.openai.com", 5, false)
slm_preload_locked("quic", "[tls] api.github.com", 2, false)
slm_preload_locked("quic", "[tls] optimizationguide-pa.googleapis.com", 4, false)
slm_preload_locked("quic", "[tls] update.googleapis.com", 7, false)
slm_preload_locked("quic", "[tls] safebrowsing.googleapis.com", 4, false)
slm_preload_locked("quic", "[tls] agentrouter.org", 40, false)
slm_preload_locked("quic", "[quic] accounts.google.com", 2, false)
slm_preload_locked("quic", "[tls] www.google.com", 2, false)
slm_preload_locked("quic", "[tls] clients.google.com", 3, false)
slm_preload_locked("quic", "[tls] accounts.google.com", 5, false)
slm_preload_locked("quic", "[tls] assets.msn.com", 15, false)
slm_preload_locked("quic", "[quic] clients.google.com", 2, false)
slm_preload_locked("quic", "[quic] update.googleapis.com", 2, false)
slm_preload_locked("quic", "[tls] api.openai.com", 3, false)
slm_preload_locked("discord", "[discord] discord voice", 2, false)
slm_preload_locked("tls", "discord.com", 5)
slm_preload_locked("tls", "google.com", 5)
slm_preload_locked("tls", "discord.gg", 5)
slm_preload_locked("tls", "discordapp.com", 5)
slm_preload_locked("tls", "googlevideo.com", 7)
slm_preload_locked("tls", "youtube.com", 8)
slm_preload_locked("tls", "youtu.be", 8)
slm_preload_locked("tls", "ytimg.com", 5)
slm_preload_locked("tls", "rutracker.org", 5)
slm_preload_locked("tls", "x.com", 5)
slm_preload_locked("tls", "spotify.com", 3)
slm_preload_locked("tls", "googleapis.com", 7)
slm_preload_locked("tls", "discord.media", 2)
slm_preload_locked("tls", "twitch.tv", 3)
slm_preload_locked("tls", "steampowered.com", 2)
slm_preload_locked("tls", "github.com", 3)
slm_preload_locked("tls", "steamcommunity.com", 9)
slm_preload_locked("tls", "githubusercontent.com", 2)
slm_preload_locked("tls", "twitchcdn.net", 2)
slm_preload_locked("tls", "gstatic.com", 2)
slm_preload_locked("tls", "ggpht.com", 2)
slm_preload_locked("tls", "discordapp.net", 2)
slm_preload_locked("tls", "roblox.com", 2)
slm_preload_locked("tls", "googletagmanager.com", 2)
slm_preload_locked("tls", "google-analytics.com", 2)
slm_preload_history("tls", "discord.com", 2, 27, 10)
slm_preload_history("tls", "discord.com", 3, 5, 7)
slm_preload_history("tls", "discord.com", 4, 0, 4)
slm_preload_history("tls", "discord.com", 5, 11, 2)
slm_preload_history("tls", "google.com", 2, 63, 34)
slm_preload_history("tls", "google.com", 3, 286, 1)
slm_preload_history("tls", "google.com", 4, 0, 1)
slm_preload_history("tls", "google.com", 5, 7, 0)
slm_preload_history("tls", "146.75.0.0", 1, 1, 0)
slm_preload_history("tls", "cloudflare-dns.com", 2, 28, 5)
slm_preload_history("tls", "cloudflare-dns.com", 3, 279, 2)
slm_preload_history("tls", "cloudflare-dns.com", 4, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 5, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 6, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 7, 17, 3)
slm_preload_history("tls", "cloudflare-dns.com", 8, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 9, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 10, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 11, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 12, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 13, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 14, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 15, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 16, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 17, 13, 3)
slm_preload_history("tls", "cloudflare-dns.com", 18, 5, 3)
slm_preload_history("tls", "cloudflare-dns.com", 19, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 20, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 21, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 22, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 23, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 24, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 25, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 26, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 27, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 28, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 29, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 30, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 31, 4, 3)
slm_preload_history("tls", "cloudflare-dns.com", 32, 0, 1)
slm_preload_history("tls", "cloudflare-dns.com", 33, 1, 0)
slm_preload_history("tls", "cloudflare-ech.com", 1, 14, 3)
slm_preload_history("tls", "cloudflare-ech.com", 2, 2, 3)
slm_preload_history("tls", "cloudflare-ech.com", 3, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 4, 2, 2)
slm_preload_history("tls", "cloudflare-ech.com", 5, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 6, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 7, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 8, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 9, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 10, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 11, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 12, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 13, 2, 2)
slm_preload_history("tls", "cloudflare-ech.com", 14, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 15, 6, 4)
slm_preload_history("tls", "cloudflare-ech.com", 16, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 17, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 18, 1, 2)
slm_preload_history("tls", "cloudflare-ech.com", 19, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 20, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 21, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 22, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 23, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 24, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 25, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 26, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 27, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 28, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 29, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 30, 0, 2)
slm_preload_history("tls", "cloudflare-ech.com", 31, 0, 1)
slm_preload_history("tls", "cloudflare-ech.com", 32, 0, 1)
slm_preload_history("tls", "cloudflare-ech.com", 33, 2, 1)
slm_preload_history("tls", "cloudflare-ech.com", 34, 0, 1)
slm_preload_history("tls", "cloudflare-ech.com", 35, 1, 0)
slm_preload_history("tls", "discord.gg", 2, 4, 3)
slm_preload_history("tls", "discord.gg", 3, 1, 3)
slm_preload_history("tls", "discord.gg", 4, 0, 2)
slm_preload_history("tls", "discord.gg", 5, 5, 0)
slm_preload_history("tls", "amazonaws.com", 2, 39, 1)
slm_preload_history("tls", "amazonaws.com", 3, 2, 0)
slm_preload_history("tls", "notionusercontent.com", 1, 5, 5)
slm_preload_history("tls", "notionusercontent.com", 2, 1, 3)
slm_preload_history("tls", "notionusercontent.com", 3, 3, 2)
slm_preload_history("tls", "notionusercontent.com", 4, 1, 1)
slm_preload_history("tls", "discordapp.com", 2, 0, 2)
slm_preload_history("tls", "discordapp.com", 3, 0, 2)
slm_preload_history("tls", "discordapp.com", 4, 0, 1)
slm_preload_history("tls", "discordapp.com", 5, 4, 0)
slm_preload_history("tls", "telegram.org", 2, 5, 4)
slm_preload_history("tls", "telegram.org", 3, 2, 3)
slm_preload_history("tls", "telegram.org", 4, 0, 1)
slm_preload_history("tls", "telegram.org", 5, 1, 0)
slm_preload_history("tls", "googlevideo.com", 2, 17, 35)
slm_preload_history("tls", "googlevideo.com", 3, 7, 10)
slm_preload_history("tls", "googlevideo.com", 4, 3, 5)
slm_preload_history("tls", "googlevideo.com", 5, 0, 4)
slm_preload_history("tls", "googlevideo.com", 6, 0, 1)
slm_preload_history("tls", "googlevideo.com", 7, 2, 1)
slm_preload_history("tls", "youtube.com", 2, 19, 32)
slm_preload_history("tls", "youtube.com", 3, 6, 9)
slm_preload_history("tls", "youtube.com", 4, 2, 10)
slm_preload_history("tls", "youtube.com", 5, 0, 7)
slm_preload_history("tls", "youtube.com", 6, 0, 5)
slm_preload_history("tls", "youtube.com", 7, 0, 5)
slm_preload_history("tls", "youtube.com", 8, 8, 6)
slm_preload_history("tls", "youtube.com", 9, 0, 4)
slm_preload_history("tls", "youtube.com", 10, 1, 3)
slm_preload_history("tls", "youtu.be", 2, 0, 2)
slm_preload_history("tls", "youtu.be", 3, 1, 2)
slm_preload_history("tls", "youtu.be", 4, 0, 1)
slm_preload_history("tls", "youtu.be", 5, 1, 1)
slm_preload_history("tls", "youtu.be", 6, 0, 1)
slm_preload_history("tls", "youtu.be", 7, 0, 1)
slm_preload_history("tls", "youtu.be", 8, 1, 0)
slm_preload_history("tls", "notion.com", 1, 12, 15)
slm_preload_history("tls", "notion.com", 2, 2, 7)
slm_preload_history("tls", "notion.com", 3, 3, 5)
slm_preload_history("tls", "notion.com", 4, 2, 5)
slm_preload_history("tls", "notion.com", 5, 1, 5)
slm_preload_history("tls", "notion.com", 6, 0, 4)
slm_preload_history("tls", "notion.com", 7, 0, 4)
slm_preload_history("tls", "notion.com", 8, 0, 4)
slm_preload_history("tls", "notion.com", 9, 0, 4)
slm_preload_history("tls", "notion.com", 10, 0, 4)
slm_preload_history("tls", "notion.com", 11, 0, 4)
slm_preload_history("tls", "notion.com", 12, 0, 4)
slm_preload_history("tls", "notion.com", 13, 1, 4)
slm_preload_history("tls", "notion.com", 14, 0, 4)
slm_preload_history("tls", "notion.com", 15, 0, 4)
slm_preload_history("tls", "notion.com", 16, 0, 4)
slm_preload_history("tls", "notion.com", 17, 0, 4)
slm_preload_history("tls", "notion.com", 18, 0, 4)
slm_preload_history("tls", "notion.com", 19, 0, 4)
slm_preload_history("tls", "notion.com", 20, 0, 4)
slm_preload_history("tls", "notion.com", 21, 0, 4)
slm_preload_history("tls", "notion.com", 22, 0, 4)
slm_preload_history("tls", "notion.com", 23, 0, 4)
slm_preload_history("tls", "notion.com", 24, 0, 4)
slm_preload_history("tls", "notion.com", 25, 0, 4)
slm_preload_history("tls", "notion.com", 26, 0, 4)
slm_preload_history("tls", "notion.com", 27, 0, 4)
slm_preload_history("tls", "notion.com", 28, 0, 4)
slm_preload_history("tls", "notion.com", 29, 0, 4)
slm_preload_history("tls", "notion.com", 30, 2, 4)
slm_preload_history("tls", "notion.com", 31, 0, 4)
slm_preload_history("tls", "notion.com", 32, 0, 4)
slm_preload_history("tls", "notion.com", 33, 2, 4)
slm_preload_history("tls", "notion.com", 34, 0, 4)
slm_preload_history("tls", "notion.com", 35, 2, 3)
slm_preload_history("tls", "notion.com", 36, 1, 3)
slm_preload_history("tls", "notion.com", 37, 0, 3)
slm_preload_history("tls", "notion.com", 38, 0, 3)
slm_preload_history("tls", "notion.com", 39, 0, 3)
slm_preload_history("tls", "notion.com", 40, 0, 3)
slm_preload_history("tls", "notion.com", 41, 0, 3)
slm_preload_history("tls", "notion.com", 42, 0, 3)
slm_preload_history("tls", "notion.com", 43, 0, 3)
slm_preload_history("tls", "notion.com", 44, 0, 3)
slm_preload_history("tls", "notion.com", 45, 0, 3)
slm_preload_history("tls", "notion.com", 46, 0, 3)
slm_preload_history("tls", "notion.com", 47, 0, 3)
slm_preload_history("tls", "notion.com", 48, 0, 3)
slm_preload_history("tls", "notion.com", 49, 0, 3)
slm_preload_history("tls", "notion.com", 50, 0, 3)
slm_preload_history("tls", "notion.com", 51, 0, 3)
slm_preload_history("tls", "notion.com", 52, 0, 3)
slm_preload_history("tls", "notion.com", 53, 0, 3)
slm_preload_history("tls", "notion.com", 54, 0, 3)
slm_preload_history("tls", "notion.com", 55, 0, 3)
slm_preload_history("tls", "notion.com", 56, 0, 3)
slm_preload_history("tls", "notion.com", 57, 0, 3)
slm_preload_history("tls", "notion.com", 58, 0, 3)
slm_preload_history("tls", "notion.com", 59, 0, 3)
slm_preload_history("tls", "notion.com", 60, 0, 3)
slm_preload_history("tls", "notion.com", 61, 0, 3)
slm_preload_history("tls", "notion.com", 62, 0, 3)
slm_preload_history("tls", "notion.com", 63, 0, 3)
slm_preload_history("tls", "notion.com", 64, 0, 3)
slm_preload_history("tls", "notion.com", 65, 0, 3)
slm_preload_history("tls", "notion.com", 66, 1, 3)
slm_preload_history("tls", "notion.com", 67, 0, 3)
slm_preload_history("tls", "notion.com", 68, 0, 2)
slm_preload_history("tls", "notion.com", 69, 0, 2)
slm_preload_history("tls", "notion.com", 70, 0, 2)
slm_preload_history("tls", "notion.com", 71, 0, 2)
slm_preload_history("tls", "notion.com", 72, 0, 2)
slm_preload_history("tls", "notion.com", 73, 0, 2)
slm_preload_history("tls", "notion.com", 74, 0, 2)
slm_preload_history("tls", "notion.com", 75, 0, 2)
slm_preload_history("tls", "notion.com", 76, 0, 2)
slm_preload_history("tls", "notion.com", 77, 0, 2)
slm_preload_history("tls", "notion.com", 78, 0, 2)
slm_preload_history("tls", "notion.com", 79, 0, 2)
slm_preload_history("tls", "notion.com", 80, 0, 2)
slm_preload_history("tls", "notion.com", 81, 0, 2)
slm_preload_history("tls", "notion.com", 82, 0, 2)
slm_preload_history("tls", "notion.com", 83, 0, 2)
slm_preload_history("tls", "notion.com", 84, 0, 2)
slm_preload_history("tls", "notion.com", 85, 0, 2)
slm_preload_history("tls", "notion.com", 86, 0, 2)
slm_preload_history("tls", "notion.com", 87, 0, 2)
slm_preload_history("tls", "notion.com", 88, 0, 2)
slm_preload_history("tls", "notion.com", 89, 0, 2)
slm_preload_history("tls", "notion.com", 90, 0, 2)
slm_preload_history("tls", "notion.com", 91, 0, 2)
slm_preload_history("tls", "notion.com", 92, 0, 2)
slm_preload_history("tls", "notion.com", 93, 0, 2)
slm_preload_history("tls", "notion.com", 94, 4, 4)
slm_preload_history("tls", "notion.com", 95, 0, 2)
slm_preload_history("tls", "notion.com", 96, 0, 2)
slm_preload_history("tls", "notion.com", 97, 0, 2)
slm_preload_history("tls", "notion.com", 98, 0, 2)
slm_preload_history("tls", "notion.com", 99, 0, 2)
slm_preload_history("tls", "notion.com", 100, 0, 2)
slm_preload_history("tls", "notion.com", 101, 0, 2)
slm_preload_history("tls", "notion.com", 102, 0, 2)
slm_preload_history("tls", "notion.com", 103, 0, 2)
slm_preload_history("tls", "notion.com", 104, 0, 2)
slm_preload_history("tls", "notion.com", 105, 0, 2)
slm_preload_history("tls", "notion.com", 106, 0, 2)
slm_preload_history("tls", "notion.com", 107, 0, 2)
slm_preload_history("tls", "notion.com", 108, 0, 2)
slm_preload_history("tls", "notion.com", 109, 0, 2)
slm_preload_history("tls", "notion.com", 110, 0, 2)
slm_preload_history("tls", "notion.com", 111, 0, 2)
slm_preload_history("tls", "notion.com", 112, 0, 2)
slm_preload_history("tls", "notion.com", 113, 2, 2)
slm_preload_history("tls", "notion.com", 114, 0, 2)
slm_preload_history("tls", "notion.com", 115, 0, 2)
slm_preload_history("tls", "notion.com", 116, 0, 2)
slm_preload_history("tls", "notion.com", 117, 0, 2)
slm_preload_history("tls", "notion.com", 118, 0, 2)
slm_preload_history("tls", "notion.com", 119, 0, 2)
slm_preload_history("tls", "notion.com", 120, 0, 2)
slm_preload_history("tls", "notion.com", 121, 0, 2)
slm_preload_history("tls", "notion.com", 122, 8, 5)
slm_preload_history("tls", "notion.com", 123, 0, 2)
slm_preload_history("tls", "notion.com", 124, 0, 2)
slm_preload_history("tls", "notion.com", 125, 0, 2)
slm_preload_history("tls", "notion.com", 126, 0, 2)
slm_preload_history("tls", "notion.com", 127, 0, 2)
slm_preload_history("tls", "notion.com", 128, 0, 2)
slm_preload_history("tls", "notion.com", 129, 0, 2)
slm_preload_history("tls", "notion.com", 130, 0, 2)
slm_preload_history("tls", "notion.com", 131, 0, 2)
slm_preload_history("tls", "notion.com", 132, 0, 2)
slm_preload_history("tls", "notion.com", 133, 0, 2)
slm_preload_history("tls", "notion.com", 134, 1, 2)
slm_preload_history("tls", "notion.com", 135, 0, 2)
slm_preload_history("tls", "notion.com", 136, 0, 2)
slm_preload_history("tls", "notion.com", 137, 0, 1)
slm_preload_history("tls", "notion.com", 138, 0, 1)
slm_preload_history("tls", "notion.com", 139, 1, 0)
slm_preload_history("tls", "cloudflare.com", 2, 58, 4)
slm_preload_history("tls", "cloudflare.com", 3, 0, 2)
slm_preload_history("tls", "cloudflare.com", 4, 0, 1)
slm_preload_history("tls", "cloudflare.com", 5, 0, 1)
slm_preload_history("tls", "cloudflare.com", 6, 0, 1)
slm_preload_history("tls", "cloudflare.com", 7, 2, 1)
slm_preload_history("tls", "cloudflare.com", 8, 0, 1)
slm_preload_history("tls", "cloudflare.com", 9, 0, 1)
slm_preload_history("tls", "cloudflare.com", 10, 0, 1)
slm_preload_history("tls", "cloudflare.com", 11, 1, 1)
slm_preload_history("tls", "cloudflare.com", 12, 13, 1)
slm_preload_history("tls", "ytimg.com", 2, 5, 31)
slm_preload_history("tls", "ytimg.com", 3, 0, 3)
slm_preload_history("tls", "ytimg.com", 4, 0, 1)
slm_preload_history("tls", "ytimg.com", 5, 1, 1)
slm_preload_history("tls", "ytimg.com", 6, 0, 1)
slm_preload_history("tls", "ytimg.com", 7, 0, 1)
slm_preload_history("tls", "ytimg.com", 8, 1, 1)
slm_preload_history("tls", "ytimg.com", 9, 0, 1)
slm_preload_history("tls", "ytimg.com", 10, 1, 1)
slm_preload_history("tls", "ytimg.com", 11, 0, 1)
slm_preload_history("tls", "rutracker.org", 2, 1, 2)
slm_preload_history("tls", "rutracker.org", 3, 0, 2)
slm_preload_history("tls", "rutracker.org", 4, 0, 1)
slm_preload_history("tls", "rutracker.org", 5, 5, 1)
slm_preload_history("tls", "battle.net", 1, 72, 9)
slm_preload_history("tls", "battle.net", 2, 4, 6)
slm_preload_history("tls", "battle.net", 3, 0, 3)
slm_preload_history("tls", "battle.net", 4, 0, 3)
slm_preload_history("tls", "battle.net", 5, 0, 3)
slm_preload_history("tls", "battle.net", 6, 0, 3)
slm_preload_history("tls", "battle.net", 7, 0, 3)
slm_preload_history("tls", "battle.net", 8, 0, 3)
slm_preload_history("tls", "battle.net", 9, 0, 3)
slm_preload_history("tls", "battle.net", 10, 0, 3)
slm_preload_history("tls", "battle.net", 11, 0, 3)
slm_preload_history("tls", "battle.net", 12, 0, 3)
slm_preload_history("tls", "battle.net", 13, 0, 2)
slm_preload_history("tls", "battle.net", 14, 0, 2)
slm_preload_history("tls", "battle.net", 15, 0, 2)
slm_preload_history("tls", "battle.net", 16, 0, 2)
slm_preload_history("tls", "battle.net", 17, 0, 2)
slm_preload_history("tls", "battle.net", 18, 0, 2)
slm_preload_history("tls", "battle.net", 19, 0, 2)
slm_preload_history("tls", "battle.net", 20, 0, 2)
slm_preload_history("tls", "battle.net", 21, 0, 2)
slm_preload_history("tls", "battle.net", 22, 0, 2)
slm_preload_history("tls", "battle.net", 23, 0, 2)
slm_preload_history("tls", "battle.net", 24, 0, 2)
slm_preload_history("tls", "battle.net", 25, 0, 2)
slm_preload_history("tls", "battle.net", 26, 0, 2)
slm_preload_history("tls", "battle.net", 27, 0, 2)
slm_preload_history("tls", "battle.net", 28, 0, 2)
slm_preload_history("tls", "battle.net", 29, 0, 2)
slm_preload_history("tls", "battle.net", 30, 0, 2)
slm_preload_history("tls", "battle.net", 31, 0, 2)
slm_preload_history("tls", "battle.net", 32, 0, 2)
slm_preload_history("tls", "battle.net", 33, 0, 2)
slm_preload_history("tls", "battle.net", 34, 0, 2)
slm_preload_history("tls", "battle.net", 35, 0, 2)
slm_preload_history("tls", "battle.net", 36, 0, 2)
slm_preload_history("tls", "battle.net", 37, 0, 2)
slm_preload_history("tls", "battle.net", 38, 0, 2)
slm_preload_history("tls", "battle.net", 39, 0, 2)
slm_preload_history("tls", "battle.net", 40, 0, 2)
slm_preload_history("tls", "battle.net", 41, 0, 2)
slm_preload_history("tls", "battle.net", 42, 0, 2)
slm_preload_history("tls", "battle.net", 43, 0, 2)
slm_preload_history("tls", "battle.net", 44, 0, 2)
slm_preload_history("tls", "battle.net", 45, 0, 2)
slm_preload_history("tls", "battle.net", 46, 0, 2)
slm_preload_history("tls", "battle.net", 47, 0, 1)
slm_preload_history("tls", "battle.net", 48, 0, 1)
slm_preload_history("tls", "battle.net", 49, 0, 1)
slm_preload_history("tls", "battle.net", 50, 0, 1)
slm_preload_history("tls", "battle.net", 51, 0, 1)
slm_preload_history("tls", "battle.net", 52, 0, 1)
slm_preload_history("tls", "battle.net", 53, 0, 1)
slm_preload_history("tls", "battle.net", 54, 0, 1)
slm_preload_history("tls", "battle.net", 55, 0, 1)
slm_preload_history("tls", "battle.net", 56, 0, 1)
slm_preload_history("tls", "battle.net", 57, 0, 1)
slm_preload_history("tls", "battle.net", 58, 0, 1)
slm_preload_history("tls", "battle.net", 59, 0, 1)
slm_preload_history("tls", "battle.net", 60, 0, 1)
slm_preload_history("tls", "battle.net", 61, 0, 1)
slm_preload_history("tls", "battle.net", 62, 0, 1)
slm_preload_history("tls", "battle.net", 63, 0, 1)
slm_preload_history("tls", "battle.net", 64, 0, 1)
slm_preload_history("tls", "battle.net", 65, 0, 1)
slm_preload_history("tls", "battle.net", 66, 0, 1)
slm_preload_history("tls", "battle.net", 67, 0, 1)
slm_preload_history("tls", "x.com", 2, 0, 2)
slm_preload_history("tls", "x.com", 3, 0, 2)
slm_preload_history("tls", "x.com", 4, 0, 1)
slm_preload_history("tls", "x.com", 5, 1, 0)
slm_preload_history("tls", "spotify.com", 2, 13, 9)
slm_preload_history("tls", "spotify.com", 3, 4, 2)
slm_preload_history("tls", "googleapis.com", 2, 18, 107)
slm_preload_history("tls", "googleapis.com", 3, 1, 3)
slm_preload_history("tls", "googleapis.com", 4, 13, 5)
slm_preload_history("tls", "googleapis.com", 5, 1, 1)
slm_preload_history("tls", "googleapis.com", 6, 0, 1)
slm_preload_history("tls", "googleapis.com", 7, 8, 1)
slm_preload_history("tls", "nvidia.com", 1, 11, 9)
slm_preload_history("tls", "nvidia.com", 2, 7, 8)
slm_preload_history("tls", "nvidia.com", 3, 3, 6)
slm_preload_history("tls", "nvidia.com", 4, 4, 5)
slm_preload_history("tls", "nvidia.com", 5, 1, 2)
slm_preload_history("tls", "nvidia.com", 6, 1, 2)
slm_preload_history("tls", "nvidia.com", 7, 0, 1)
slm_preload_history("tls", "nvidia.com", 8, 0, 1)
slm_preload_history("tls", "nvidia.com", 9, 0, 1)
slm_preload_history("tls", "nvidia.com", 10, 0, 1)
slm_preload_history("tls", "nvidia.com", 11, 1, 1)
slm_preload_history("tls", "nvidia.com", 12, 0, 1)
slm_preload_history("tls", "nvidia.com", 13, 0, 1)
slm_preload_history("tls", "nvidia.com", 14, 0, 1)
slm_preload_history("tls", "office.net", 1, 6, 3)
slm_preload_history("tls", "office.net", 2, 7, 4)
slm_preload_history("tls", "office.net", 3, 48, 3)
slm_preload_history("tls", "lencr.org", 1, 2, 3)
slm_preload_history("tls", "lencr.org", 2, 0, 3)
slm_preload_history("tls", "lencr.org", 3, 0, 3)
slm_preload_history("tls", "lencr.org", 4, 0, 3)
slm_preload_history("tls", "lencr.org", 5, 0, 2)
slm_preload_history("tls", "lencr.org", 6, 0, 2)
slm_preload_history("tls", "lencr.org", 7, 0, 1)
slm_preload_history("tls", "lencr.org", 8, 0, 1)
slm_preload_history("tls", "lencr.org", 9, 0, 1)
slm_preload_history("tls", "lencr.org", 10, 0, 1)
slm_preload_history("tls", "lencr.org", 11, 0, 1)
slm_preload_history("tls", "lencr.org", 12, 0, 1)
slm_preload_history("tls", "pki.goog", 1, 0, 3)
slm_preload_history("tls", "pki.goog", 2, 0, 2)
slm_preload_history("tls", "pki.goog", 3, 0, 2)
slm_preload_history("tls", "discord.media", 2, 5, 3)
slm_preload_history("tls", "104.29.0.0", 1, 60, 0)
slm_preload_history("tls", "239.255.0.0", 1, 0, 18)
slm_preload_history("tls", "239.255.0.0", 2, 0, 18)
slm_preload_history("tls", "239.255.0.0", 3, 0, 18)
slm_preload_history("tls", "239.255.0.0", 4, 0, 18)
slm_preload_history("tls", "239.255.0.0", 5, 0, 18)
slm_preload_history("tls", "239.255.0.0", 6, 0, 18)
slm_preload_history("tls", "239.255.0.0", 7, 0, 18)
slm_preload_history("tls", "239.255.0.0", 8, 0, 18)
slm_preload_history("tls", "239.255.0.0", 9, 0, 18)
slm_preload_history("tls", "239.255.0.0", 10, 0, 18)
slm_preload_history("tls", "239.255.0.0", 11, 0, 18)
slm_preload_history("tls", "239.255.0.0", 12, 0, 18)
slm_preload_history("tls", "239.255.0.0", 13, 0, 17)
slm_preload_history("tls", "239.255.0.0", 14, 0, 17)
slm_preload_history("tls", "239.255.0.0", 15, 0, 15)
slm_preload_history("tls", "239.255.0.0", 16, 0, 14)
slm_preload_history("tls", "239.255.0.0", 17, 0, 12)
slm_preload_history("tls", "239.255.0.0", 18, 0, 12)
slm_preload_history("tls", "239.255.0.0", 19, 0, 12)
slm_preload_history("tls", "239.255.0.0", 20, 0, 12)
slm_preload_history("tls", "239.255.0.0", 21, 0, 13)
slm_preload_history("tls", "239.255.0.0", 22, 0, 12)
slm_preload_history("tls", "239.255.0.0", 23, 0, 9)
slm_preload_history("tls", "239.255.0.0", 24, 0, 9)
slm_preload_history("tls", "239.255.0.0", 25, 0, 9)
slm_preload_history("tls", "239.255.0.0", 26, 0, 9)
slm_preload_history("tls", "239.255.0.0", 27, 0, 9)
slm_preload_history("tls", "239.255.0.0", 28, 0, 9)
slm_preload_history("tls", "239.255.0.0", 29, 0, 9)
slm_preload_history("tls", "239.255.0.0", 30, 0, 9)
slm_preload_history("tls", "239.255.0.0", 31, 0, 9)
slm_preload_history("tls", "239.255.0.0", 32, 0, 9)
slm_preload_history("tls", "239.255.0.0", 33, 0, 9)
slm_preload_history("tls", "239.255.0.0", 34, 0, 9)
slm_preload_history("tls", "239.255.0.0", 35, 0, 9)
slm_preload_history("tls", "239.255.0.0", 36, 0, 9)
slm_preload_history("tls", "239.255.0.0", 37, 0, 9)
slm_preload_history("tls", "239.255.0.0", 38, 0, 9)
slm_preload_history("tls", "239.255.0.0", 39, 0, 9)
slm_preload_history("tls", "239.255.0.0", 40, 0, 9)
slm_preload_history("tls", "239.255.0.0", 41, 0, 9)
slm_preload_history("tls", "239.255.0.0", 42, 0, 9)
slm_preload_history("tls", "239.255.0.0", 43, 0, 9)
slm_preload_history("tls", "239.255.0.0", 44, 0, 9)
slm_preload_history("tls", "239.255.0.0", 45, 0, 9)
slm_preload_history("tls", "239.255.0.0", 46, 0, 9)
slm_preload_history("tls", "239.255.0.0", 47, 0, 9)
slm_preload_history("tls", "239.255.0.0", 48, 0, 9)
slm_preload_history("tls", "239.255.0.0", 49, 0, 9)
slm_preload_history("tls", "239.255.0.0", 50, 0, 10)
slm_preload_history("tls", "239.255.0.0", 51, 0, 9)
slm_preload_history("tls", "239.255.0.0", 52, 0, 9)
slm_preload_history("tls", "239.255.0.0", 53, 0, 9)
slm_preload_history("tls", "239.255.0.0", 54, 0, 9)
slm_preload_history("tls", "239.255.0.0", 55, 0, 9)
slm_preload_history("tls", "239.255.0.0", 56, 0, 9)
slm_preload_history("tls", "239.255.0.0", 57, 0, 9)
slm_preload_history("tls", "239.255.0.0", 58, 0, 9)
slm_preload_history("tls", "239.255.0.0", 59, 0, 9)
slm_preload_history("tls", "239.255.0.0", 60, 0, 9)
slm_preload_history("tls", "239.255.0.0", 61, 0, 9)
slm_preload_history("tls", "239.255.0.0", 62, 0, 9)
slm_preload_history("tls", "239.255.0.0", 63, 0, 9)
slm_preload_history("tls", "239.255.0.0", 64, 0, 9)
slm_preload_history("tls", "239.255.0.0", 65, 0, 9)
slm_preload_history("tls", "239.255.0.0", 66, 0, 9)
slm_preload_history("tls", "239.255.0.0", 67, 0, 9)
slm_preload_history("tls", "twitch.tv", 2, 41, 13)
slm_preload_history("tls", "twitch.tv", 3, 59, 5)
slm_preload_history("tls", "twitch.tv", 4, 3, 4)
slm_preload_history("tls", "twitch.tv", 5, 3, 3)
slm_preload_history("tls", "twitch.tv", 6, 2, 1)
slm_preload_history("tls", "twitch.tv", 7, 1, 1)
slm_preload_history("tls", "twitch.tv", 8, 0, 1)
slm_preload_history("tls", "twitch.tv", 9, 0, 1)
slm_preload_history("tls", "twitch.tv", 10, 0, 1)
slm_preload_history("tls", "twitch.tv", 11, 1, 1)
slm_preload_history("tls", "cloud.microsoft", 1, 3, 3)
slm_preload_history("tls", "cloud.microsoft", 2, 9, 4)
slm_preload_history("tls", "cloud.microsoft", 3, 36, 2)
slm_preload_history("tls", "gamepass.com", 1, 5, 3)
slm_preload_history("tls", "gamepass.com", 2, 4, 3)
slm_preload_history("tls", "gamepass.com", 3, 16, 10)
slm_preload_history("tls", "gamepass.com", 4, 2, 2)
slm_preload_history("tls", "gamepass.com", 5, 2, 1)
slm_preload_history("tls", "gamepass.com", 6, 2, 1)
slm_preload_history("tls", "gamepass.com", 7, 1, 1)
slm_preload_history("tls", "gamepass.com", 8, 1, 1)
slm_preload_history("tls", "gamepass.com", 9, 0, 1)
slm_preload_history("tls", "gamepass.com", 10, 0, 1)
slm_preload_history("tls", "gamepass.com", 11, 1, 1)
slm_preload_history("tls", "gamepass.com", 12, 1, 1)
slm_preload_history("tls", "gamepass.com", 13, 1, 1)
slm_preload_history("tls", "7tv.io", 1, 2, 4)
slm_preload_history("tls", "7tv.io", 2, 1, 4)
slm_preload_history("tls", "7tv.io", 3, 224, 18)
slm_preload_history("tls", "7tv.io", 4, 0, 3)
slm_preload_history("tls", "7tv.io", 5, 3, 3)
slm_preload_history("tls", "7tv.io", 6, 7, 5)
slm_preload_history("tls", "7tv.io", 7, 0, 1)
slm_preload_history("tls", "7tv.io", 8, 0, 1)
slm_preload_history("tls", "7tv.io", 9, 0, 1)
slm_preload_history("tls", "7tv.io", 10, 0, 1)
slm_preload_history("tls", "7tv.io", 11, 13, 2)
slm_preload_history("tls", "7tv.app", 1, 1, 4)
slm_preload_history("tls", "7tv.app", 2, 1, 1)
slm_preload_history("tls", "7tv.app", 3, 0, 1)
slm_preload_history("tls", "7tv.app", 4, 1, 0)
slm_preload_history("tls", "ovh.net", 1, 0, 1)
slm_preload_history("tls", "ovh.net", 2, 1, 0)
slm_preload_history("tls", "industrialport.net", 1, 0, 1)
slm_preload_history("tls", "industrialport.net", 2, 1, 0)
slm_preload_history("tls", "audioeye.com", 1, 1, 0)
slm_preload_history("tls", "windowsupdate.com", 1, 0, 3)
slm_preload_history("tls", "windowsupdate.com", 2, 0, 1)
slm_preload_history("tls", "getmilana.ai", 1, 7, 2)
slm_preload_history("tls", "getmilana.ai", 2, 0, 1)
slm_preload_history("tls", "getmilana.ai", 3, 0, 1)
slm_preload_history("tls", "getmilana.ai", 4, 0, 1)
slm_preload_history("tls", "discord voice", 2, 4, 0)
slm_preload_history("tls", "blizzard.com", 1, 56, 0)
slm_preload_history("tls", "akamaized.net", 1, 7, 0)
slm_preload_history("tls", "notion.so", 1, 2, 3)
slm_preload_history("tls", "notion.so", 2, 1, 2)
slm_preload_history("tls", "notion.so", 3, 0, 1)
slm_preload_history("tls", "steampowered.com", 2, 0, 2)
slm_preload_history("tls", "steampowered.com", 3, 0, 1)
slm_preload_history("tls", "xboxlive.com", 1, 18, 5)
slm_preload_history("tls", "xboxlive.com", 2, 1, 2)
slm_preload_history("tls", "xboxlive.com", 3, 2, 0)
slm_preload_history("tls", "epicgames.com", 1, 1, 1)
slm_preload_history("tls", "epicgames.dev", 1, 1, 1)
slm_preload_history("tls", "epicgames.dev", 2, 1, 1)
slm_preload_history("tls", "epicgames.dev", 3, 2, 1)
slm_preload_history("tls", "epicgames.dev", 4, 1, 1)
slm_preload_history("tls", "github.com", 2, 5, 3)
slm_preload_history("tls", "github.com", 3, 35, 4)
slm_preload_history("tls", "github.com", 4, 0, 2)
slm_preload_history("tls", "github.com", 5, 1, 2)
slm_preload_history("tls", "github.com", 6, 0, 1)
slm_preload_history("tls", "github.com", 7, 0, 1)
slm_preload_history("tls", "steaminventoryhelper.com", 1, 18, 6)
slm_preload_history("tls", "steaminventoryhelper.com", 2, 0, 4)
slm_preload_history("tls", "steaminventoryhelper.com", 3, 1, 3)
slm_preload_history("tls", "steaminventoryhelper.com", 4, 1, 3)
slm_preload_history("tls", "steaminventoryhelper.com", 5, 0, 1)
slm_preload_history("tls", "steaminventoryhelper.com", 6, 0, 1)
slm_preload_history("tls", "steaminventoryhelper.com", 7, 0, 1)
slm_preload_history("tls", "steamcommunity.com", 2, 37, 26)
slm_preload_history("tls", "steamcommunity.com", 3, 8, 5)
slm_preload_history("tls", "steamcommunity.com", 4, 0, 2)
slm_preload_history("tls", "steamcommunity.com", 5, 2, 2)
slm_preload_history("tls", "steamcommunity.com", 6, 1, 1)
slm_preload_history("tls", "steamcommunity.com", 7, 2, 1)
slm_preload_history("tls", "steamcommunity.com", 8, 0, 1)
slm_preload_history("tls", "steamcommunity.com", 9, 9, 4)
slm_preload_history("tls", "155.133.0.0", 1, 11, 0)
slm_preload_history("tls", "162.254.0.0", 1, 8, 0)
slm_preload_history("tls", "103.28.0.0", 1, 1, 0)
slm_preload_history("tls", "185.25.0.0", 1, 2, 0)
slm_preload_history("tls", "103.10.0.0", 1, 2, 0)
slm_preload_history("tls", "146.66.0.0", 1, 2, 0)
slm_preload_history("tls", "205.196.0.0", 1, 1, 0)
slm_preload_history("tls", "45.121.0.0", 1, 1, 0)
slm_preload_history("tls", "bhvrdbd.com", 1, 0, 1)
slm_preload_history("tls", "bhvrdbd.com", 2, 12, 0)
slm_preload_history("tls", "3.249.0.0", 2, 0, 1)
slm_preload_history("tls", "13.215.0.0", 2, 0, 1)
slm_preload_history("tls", "52.64.0.0", 2, 0, 1)
slm_preload_history("tls", "15.164.0.0", 2, 0, 1)
slm_preload_history("tls", "52.28.0.0", 2, 0, 1)
slm_preload_history("tls", "54.95.0.0", 2, 0, 1)
slm_preload_history("tls", "3.88.0.0", 2, 0, 1)
slm_preload_history("tls", "56.125.0.0", 2, 0, 1)
slm_preload_history("tls", "43.198.0.0", 2, 0, 1)
slm_preload_history("tls", "44.248.0.0", 2, 0, 1)
slm_preload_history("tls", "18.217.0.0", 2, 0, 1)
slm_preload_history("tls", "15.157.0.0", 2, 0, 1)
slm_preload_history("tls", "13.57.0.0", 2, 0, 1)
slm_preload_history("tls", "18.133.0.0", 2, 0, 1)
slm_preload_history("tls", "3.6.0.0", 2, 0, 1)
slm_preload_history("tls", "geforce.com", 1, 1, 2)
slm_preload_history("tls", "geforce.com", 2, 1, 1)
slm_preload_history("tls", "geforce.com", 3, 1, 1)
slm_preload_history("tls", "geforce.com", 4, 1, 1)
slm_preload_history("tls", "bingapis.com", 1, 3, 3)
slm_preload_history("tls", "bingapis.com", 2, 3, 3)
slm_preload_history("tls", "githubassets.com", 1, 18, 3)
slm_preload_history("tls", "githubassets.com", 2, 6, 1)
slm_preload_history("tls", "githubassets.com", 3, 0, 1)
slm_preload_history("tls", "githubassets.com", 4, 1, 0)
slm_preload_history("tls", "githubusercontent.com", 2, 5, 4)
slm_preload_history("tls", "githubusercontent.com", 3, 0, 3)
slm_preload_history("tls", "githubusercontent.com", 4, 1, 2)
slm_preload_history("tls", "githubusercontent.com", 5, 0, 2)
slm_preload_history("tls", "githubusercontent.com", 6, 2, 2)
slm_preload_history("tls", "githubusercontent.com", 7, 0, 1)
slm_preload_history("tls", "bing.com", 1, 11, 3)
slm_preload_history("tls", "bing.com", 2, 3, 3)
slm_preload_history("tls", "bing.com", 3, 0, 2)
slm_preload_history("tls", "bing.com", 4, 1, 1)
slm_preload_history("tls", "bing.com", 5, 0, 1)
slm_preload_history("tls", "bing.com", 6, 0, 1)
slm_preload_history("tls", "bing.com", 7, 1, 1)
slm_preload_history("tls", "bing.com", 8, 0, 1)
slm_preload_history("tls", "bing.com", 9, 0, 1)
slm_preload_history("tls", "bing.com", 10, 0, 1)
slm_preload_history("tls", "bing.com", 11, 1, 1)
slm_preload_history("tls", "scorecardresearch.com", 1, 2, 2)
slm_preload_history("tls", "scorecardresearch.com", 2, 1, 2)
slm_preload_history("tls", "scorecardresearch.com", 3, 0, 1)
slm_preload_history("tls", "scorecardresearch.com", 4, 0, 1)
slm_preload_history("tls", "scorecardresearch.com", 5, 0, 1)
slm_preload_history("tls", "scorecardresearch.com", 6, 0, 1)
slm_preload_history("tls", "scorecardresearch.com", 7, 1, 0)
slm_preload_history("tls", "msn.com", 1, 14, 5)
slm_preload_history("tls", "msn.com", 2, 14, 8)
slm_preload_history("tls", "msn.com", 3, 6, 3)
slm_preload_history("tls", "msn.com", 4, 4, 3)
slm_preload_history("tls", "msn.com", 5, 0, 3)
slm_preload_history("tls", "msn.com", 6, 0, 2)
slm_preload_history("tls", "msn.com", 7, 13, 10)
slm_preload_history("tls", "msn.com", 8, 0, 1)
slm_preload_history("tls", "msn.com", 9, 0, 1)
slm_preload_history("tls", "msn.com", 10, 0, 1)
slm_preload_history("tls", "msn.com", 11, 0, 1)
slm_preload_history("tls", "msn.com", 12, 0, 1)
slm_preload_history("tls", "msn.com", 13, 0, 1)
slm_preload_history("tls", "msn.com", 14, 2, 1)
slm_preload_history("tls", "msn.com", 15, 4, 2)
slm_preload_history("tls", "cloudfront.net", 1, 4, 1)
slm_preload_history("tls", "localizeapi.com", 1, 4, 1)
slm_preload_history("tls", "steamdb.info", 1, 2, 0)
slm_preload_history("tls", "website-files.com", 1, 2, 1)
slm_preload_history("tls", "onetrust.com", 1, 1, 1)
slm_preload_history("tls", "vknext.net", 1, 3, 1)
slm_preload_history("tls", "vknext.net", 2, 0, 1)
slm_preload_history("tls", "betterttv.net", 1, 6, 6)
slm_preload_history("tls", "betterttv.net", 2, 0, 3)
slm_preload_history("tls", "betterttv.net", 3, 1, 3)
slm_preload_history("tls", "betterttv.net", 4, 1, 3)
slm_preload_history("tls", "betterttv.net", 5, 2, 2)
slm_preload_history("tls", "betterttv.net", 6, 1, 2)
slm_preload_history("tls", "betterttv.net", 7, 1, 1)
slm_preload_history("tls", "betterttv.net", 8, 0, 1)
slm_preload_history("tls", "betterttv.net", 9, 1, 1)
slm_preload_history("tls", "twitchcdn.net", 2, 4, 1)
slm_preload_history("tls", "twitchcdn.net", 3, 1, 1)
slm_preload_history("tls", "ttvnw.net", 1, 3, 2)
slm_preload_history("tls", "ttvnw.net", 2, 1, 1)
slm_preload_history("tls", "ttvnw.net", 3, 0, 1)
slm_preload_history("tls", "ttvnw.net", 4, 0, 1)
slm_preload_history("tls", "ttvnw.net", 5, 0, 1)
slm_preload_history("tls", "ttvnw.net", 6, 0, 1)
slm_preload_history("tls", "ttvnw.net", 7, 0, 1)
slm_preload_history("tls", "ttvnw.net", 8, 0, 1)
slm_preload_history("tls", "ttvnw.net", 9, 0, 1)
slm_preload_history("tls", "ttvnw.net", 10, 0, 1)
slm_preload_history("tls", "ttvnw.net", 11, 1, 1)
slm_preload_history("tls", "ttvnw.net", 12, 0, 1)
slm_preload_history("tls", "live-video.net", 1, 17, 4)
slm_preload_history("tls", "live-video.net", 2, 3, 2)
slm_preload_history("tls", "live-video.net", 3, 2, 1)
slm_preload_history("tls", "live-video.net", 4, 0, 1)
slm_preload_history("tls", "frankerfacez.com", 1, 1, 2)
slm_preload_history("tls", "frankerfacez.com", 2, 0, 1)
slm_preload_history("tls", "frankerfacez.com", 3, 1, 1)
slm_preload_history("tls", "frankerfacez.com", 4, 0, 1)
slm_preload_history("tls", "frankerfacez.com", 5, 1, 1)
slm_preload_history("tls", "jtvnw.net", 1, 5, 2)
slm_preload_history("tls", "jtvnw.net", 2, 1, 2)
slm_preload_history("tls", "jtvnw.net", 3, 1, 2)
slm_preload_history("tls", "jtvnw.net", 4, 1, 2)
slm_preload_history("tls", "jtvnw.net", 5, 0, 1)
slm_preload_history("tls", "jtvnw.net", 6, 0, 1)
slm_preload_history("tls", "jtvnw.net", 7, 5, 2)
slm_preload_history("tls", "gstatic.com", 2, 8, 7)
slm_preload_history("tls", "gstatic.com", 3, 1, 2)
slm_preload_history("tls", "gstatic.com", 4, 1, 2)
slm_preload_history("tls", "yastatic.net", 1, 9, 1)
slm_preload_history("tls", "yastatic.net", 2, 0, 1)
slm_preload_history("tls", "yastatic.net", 3, 1, 1)
slm_preload_history("tls", "yastatic.net", 4, 9, 5)
slm_preload_history("tls", "returnyoutubedislikeapi.com", 1, 9, 3)
slm_preload_history("tls", "returnyoutubedislikeapi.com", 2, 0, 2)
slm_preload_history("tls", "returnyoutubedislikeapi.com", 3, 0, 1)
slm_preload_history("tls", "returnyoutubedislikeapi.com", 4, 0, 1)
slm_preload_history("tls", "returnyoutubedislikeapi.com", 5, 0, 1)
slm_preload_history("tls", "returnyoutubedislikeapi.com", 6, 0, 1)
slm_preload_history("tls", "azureedge.net", 1, 5, 1)
slm_preload_history("tls", "splunkcloud.com", 1, 8, 2)
slm_preload_history("tls", "splunkcloud.com", 2, 2, 2)
slm_preload_history("tls", "splunkcloud.com", 3, 1, 1)
slm_preload_history("tls", "splunkcloud.com", 4, 0, 1)
slm_preload_history("tls", "splunkcloud.com", 5, 1, 1)
slm_preload_history("tls", "splunkcloud.com", 6, 1, 1)
slm_preload_history("tls", "bitwarden.com", 1, 7, 2)
slm_preload_history("tls", "bitwarden.com", 2, 2, 2)
slm_preload_history("tls", "bitwarden.com", 3, 0, 1)
slm_preload_history("tls", "bitwarden.com", 4, 2, 0)
slm_preload_history("tls", "gist.build", 1, 35, 0)
slm_preload_history("tls", "windows.com", 1, 124, 1)
slm_preload_history("tls", "windows.com", 2, 1, 0)
slm_preload_history("tls", "ggpht.com", 2, 2, 8)
slm_preload_history("tls", "sentry.io", 1, 40, 1)
slm_preload_history("tls", "customer.io", 1, 3, 1)
slm_preload_history("tls", "yandex.net", 1, 6, 0)
slm_preload_history("tls", "vkuseraudio.ru", 1, 1, 1)
slm_preload_history("tls", "vkuseraudio.ru", 2, 2, 0)
slm_preload_history("tls", "ext-twitch.tv", 1, 3, 1)
slm_preload_history("tls", "ajay.app", 1, 1, 0)
slm_preload_history("tls", "zg-59581ae03bf87b94aaf44136.invalid", 1, 0, 2)
slm_preload_history("tls", "zg-59581ae03bf87b94aaf44136.invalid", 2, 0, 2)
slm_preload_history("tls", "zg-59581ae03bf87b94aaf44136.invalid", 3, 0, 2)
slm_preload_history("tls", "zg-59581ae03bf87b94aaf44136.invalid", 4, 0, 2)
slm_preload_history("tls", "zg-59581ae03bf87b94aaf44136.invalid", 5, 0, 1)
slm_preload_history("tls", "zg-59581ae03bf87b94aaf44136.invalid", 6, 0, 1)
slm_preload_history("tls", "zg-c321bcdb7cfeeaafa32b4f7c.invalid", 1, 17, 2)
slm_preload_history("tls", "zg-c321bcdb7cfeeaafa32b4f7c.invalid", 2, 2, 2)
slm_preload_history("tls", "zg-c321bcdb7cfeeaafa32b4f7c.invalid", 3, 0, 1)
slm_preload_history("tls", "zg-c321bcdb7cfeeaafa32b4f7c.invalid", 4, 0, 1)
slm_preload_history("tls", "zg-c321bcdb7cfeeaafa32b4f7c.invalid", 5, 0, 1)
slm_preload_history("tls", "zg-c321bcdb7cfeeaafa32b4f7c.invalid", 6, 0, 1)
slm_preload_history("tls", "zg-c321bcdb7cfeeaafa32b4f7c.invalid", 7, 0, 1)
slm_preload_history("tls", "zg-c321bcdb7cfeeaafa32b4f7c.invalid", 8, 0, 1)
slm_preload_history("tls", "github.io", 1, 4, 1)
slm_preload_history("tls", "exp-tas.com", 1, 13, 1)
slm_preload_history("tls", "exp-tas.com", 2, 2, 1)
slm_preload_history("tls", "exp-tas.com", 3, 2, 0)
slm_preload_history("tls", "scdn.co", 2, 1, 0)
slm_preload_history("tls", "discordapp.net", 2, 2, 1)
slm_preload_history("tls", "discordapp.net", 3, 1, 1)
slm_preload_history("tls", "discordapp.net", 4, 1, 1)
slm_preload_history("tls", "20.101.0.0", 1, 1, 0)
slm_preload_history("tls", "vkuserphoto.ru", 1, 4, 2)
slm_preload_history("tls", "userapi.com", 1, 2, 0)
slm_preload_history("tls", "exitlag.net", 1, 71, 3)
slm_preload_history("tls", "exitlag.net", 2, 2, 2)
slm_preload_history("tls", "exitlag.net", 3, 3, 1)
slm_preload_history("tls", "exitlag.net", 4, 1, 1)
slm_preload_history("tls", "exitlag.net", 5, 1, 1)
slm_preload_history("tls", "exitlag.net", 6, 1, 1)
slm_preload_history("tls", "exitlag.com", 1, 6, 1)
slm_preload_history("tls", "exitlag.com", 2, 16, 0)
slm_preload_history("tls", "r2.dev", 1, 9, 1)
slm_preload_history("tls", "r2.dev", 2, 12, 0)
slm_preload_history("tls", "mixpanel.com", 1, 2, 0)
slm_preload_history("tls", "steamserver.net", 1, 1, 1)
slm_preload_history("tls", "203.23.0.0", 1, 5, 8)
slm_preload_history("tls", "203.23.0.0", 2, 16, 12)
slm_preload_history("tls", "203.23.0.0", 3, 13, 11)
slm_preload_history("tls", "203.23.0.0", 4, 120, 65)
slm_preload_history("tls", "203.23.0.0", 5, 0, 3)
slm_preload_history("tls", "203.23.0.0", 6, 20, 8)
slm_preload_history("tls", "203.23.0.0", 7, 51, 24)
slm_preload_history("tls", "office.com", 1, 0, 1)
slm_preload_history("tls", "roblox.com", 2, 14, 6)
slm_preload_history("tls", "roblox.com", 3, 0, 2)
slm_preload_history("tls", "roblox.com", 4, 0, 1)
slm_preload_history("tls", "msftconnecttest.com", 1, 0, 1)
slm_preload_history("tls", "googletagmanager.com", 2, 0, 1)
slm_preload_history("tls", "google-analytics.com", 2, 0, 1)
slm_preload_history("tls", "notion-static.com", 1, 1, 1)
slm_preload_history("tls", "signalr.net", 1, 4, 0)
slm_preload_history("tls", "34.110.0.0", 1, 0, 1)
slm_preload_history("tls", "codex.sale", 1, 6, 1)
slm_preload_history("tls", "codex.sale", 2, 1, 1)
slm_preload_history("tls", "codex.sale", 3, 104, 2)
slm_preload_history("tls", "wizebot.tv", 1, 0, 2)
slm_preload_history("tls", "wizebot.tv", 2, 0, 1)
slm_preload_history("tls", "funpay.com", 1, 0, 1)
slm_preload_history("tls", "funpay.com", 2, 2, 1)
slm_preload_history("tls", "funpay.com", 3, 1, 1)
slm_preload_history("tls", "sfunpay.com", 1, 0, 1)
slm_preload_history("tls", "sfunpay.com", 2, 0, 1)
slm_preload_history("tls", "sfunpay.com", 3, 0, 1)
slm_preload_history("tls", "sfunpay.com", 4, 0, 1)
slm_preload_history("tls", "sfunpay.com", 5, 0, 1)
slm_preload_history("tls", "sfunpay.com", 6, 0, 1)
slm_preload_history("tls", "sfunpay.com", 7, 0, 1)
slm_preload_history("tls", "sfunpay.com", 8, 0, 1)
slm_preload_history("tls", "sfunpay.com", 9, 0, 1)
slm_preload_history("tls", "sfunpay.com", 10, 0, 1)
slm_preload_history("tls", "sfunpay.com", 11, 0, 1)
slm_preload_history("tls", "sfunpay.com", 12, 0, 1)
slm_preload_history("tls", "sfunpay.com", 13, 0, 1)
slm_preload_history("tls", "sfunpay.com", 14, 0, 1)
slm_preload_history("tls", "sfunpay.com", 15, 0, 1)
slm_preload_history("tls", "sfunpay.com", 16, 0, 1)
slm_preload_history("tls", "sfunpay.com", 17, 0, 1)
slm_preload_history("tls", "sfunpay.com", 18, 0, 1)
slm_preload_history("tls", "sfunpay.com", 19, 0, 1)
slm_preload_history("tls", "sfunpay.com", 20, 0, 1)
slm_preload_history("tls", "sfunpay.com", 21, 0, 1)
slm_preload_history("tls", "sfunpay.com", 22, 0, 1)
slm_preload_history("tls", "sfunpay.com", 23, 0, 1)
slm_preload_history("tls", "sfunpay.com", 24, 0, 1)
slm_preload_history("tls", "sfunpay.com", 25, 0, 1)
slm_preload_history("tls", "sfunpay.com", 26, 0, 1)
slm_preload_history("tls", "sfunpay.com", 27, 0, 1)
slm_preload_history("tls", "sfunpay.com", 28, 0, 1)
slm_preload_history("tls", "sfunpay.com", 29, 0, 1)
slm_preload_history("tls", "sfunpay.com", 30, 5, 0)
slm_preload_history("tls", "oaistatic.com", 1, 9, 0)
slm_preload_history("tls", "77.111.102.204", 1, 7, 0)
slm_preload_history("tls", "openai.com", 1, 11, 2)
slm_preload_history("tls", "openai.com", 2, 2, 2)
slm_preload_history("tls", "openai.com", 3, 16, 1)
slm_preload_history("tls", "openai.com", 4, 1, 1)
slm_preload_history("tls", "openai.com", 5, 16, 0)
slm_preload_history("tls", "chatgpt.com", 1, 6, 2)
slm_preload_history("tls", "chatgpt.com", 2, 2, 2)
slm_preload_history("tls", "chatgpt.com", 3, 24, 1)
slm_preload_history("tls", "chatgpt.com", 4, 2, 1)
slm_preload_history("tls", "chatgpt.com", 5, 22, 0)
slm_preload_history("tls", "gvt1.com", 1, 9, 0)
slm_preload_history("tls", "vscode.dev", 1, 1, 0)
slm_preload_history("tls", "224.0.0.0", 1, 0, 3)
slm_preload_history("tls", "t.me", 2, 1, 1)
slm_preload_history("tls", "telesco.pe", 1, 1, 1)
slm_preload_history("tls", "sublimetext.com", 1, 0, 1)
slm_preload_history("tls", "tome.ge", 1, 3, 1)
slm_preload_history("tls", "agentrouter.org", 1, 3, 1)
slm_preload_history("tls", "agentrouter.org", 2, 0, 1)
slm_preload_history("tls", "agentrouter.org", 3, 0, 1)
slm_preload_history("tls", "agentrouter.org", 4, 2, 1)
slm_preload_history("tls", "agentrouter.org", 5, 0, 1)
slm_preload_history("tls", "agentrouter.org", 6, 0, 1)
slm_preload_history("tls", "agentrouter.org", 7, 0, 1)
slm_preload_history("tls", "agentrouter.org", 8, 0, 1)
slm_preload_history("tls", "agentrouter.org", 9, 0, 1)
slm_preload_history("tls", "agentrouter.org", 10, 0, 1)
slm_preload_history("tls", "agentrouter.org", 11, 0, 1)
slm_preload_history("tls", "agentrouter.org", 12, 0, 1)
slm_preload_history("tls", "agentrouter.org", 13, 1, 1)
slm_preload_history("tls", "agentrouter.org", 14, 0, 1)
slm_preload_history("tls", "agentrouter.org", 15, 0, 1)
slm_preload_history("tls", "agentrouter.org", 16, 0, 1)
slm_preload_history("tls", "agentrouter.org", 17, 0, 1)
slm_preload_history("tls", "agentrouter.org", 18, 0, 1)
slm_preload_history("tls", "agentrouter.org", 19, 0, 1)
slm_preload_history("tls", "agentrouter.org", 20, 0, 1)
slm_preload_history("tls", "agentrouter.org", 21, 0, 1)
slm_preload_history("tls", "agentrouter.org", 22, 0, 1)
slm_preload_history("tls", "agentrouter.org", 23, 0, 1)
slm_preload_history("tls", "agentrouter.org", 24, 0, 1)
slm_preload_history("tls", "agentrouter.org", 25, 0, 1)
slm_preload_history("tls", "agentrouter.org", 26, 0, 1)
slm_preload_history("tls", "agentrouter.org", 27, 0, 1)
slm_preload_history("tls", "agentrouter.org", 28, 0, 1)
slm_preload_history("tls", "agentrouter.org", 29, 0, 1)
slm_preload_history("tls", "agentrouter.org", 30, 0, 1)
slm_preload_history("tls", "agentrouter.org", 31, 0, 1)
slm_preload_history("tls", "agentrouter.org", 32, 0, 1)
slm_preload_history("tls", "agentrouter.org", 33, 0, 1)
slm_preload_history("tls", "agentrouter.org", 34, 0, 1)
slm_preload_history("tls", "agentrouter.org", 35, 0, 1)
slm_preload_history("tls", "agentrouter.org", 36, 0, 1)
slm_preload_history("tls", "agentrouter.org", 37, 0, 1)
slm_preload_history("tls", "agentrouter.org", 38, 0, 1)
slm_preload_history("tls", "agentrouter.org", 39, 0, 1)
slm_preload_history("tls", "agentrouter.org", 40, 12, 1)
slm_preload_history("tls", "comss.one", 1, 3, 1)
slm_preload_history("tls", "comss.one", 2, 0, 1)
slm_preload_history("tls", "comss.one", 3, 0, 1)
slm_preload_history("tls", "comss.one", 4, 0, 1)
slm_preload_history("tls", "comss.one", 5, 12, 3)
slm_preload_history("tls", "comss.one", 6, 1, 1)
slm_preload_history("tls", "comss.one", 7, 1, 1)
slm_preload_history("tls", "comss.one", 8, 1, 1)
slm_preload_history("tls", "comss.one", 9, 1, 1)
slm_preload_history("tls", "comss.one", 10, 1, 1)
slm_preload_history("tls", "comss.one", 11, 0, 1)
slm_preload_history("tls", "comss.one", 12, 0, 1)
slm_preload_history("tls", "comss.one", 13, 0, 1)
slm_preload_history("tls", "comss.one", 14, 0, 1)
slm_preload_history("tls", "comss.one", 15, 0, 1)
slm_preload_history("tls", "comss.one", 16, 0, 1)
slm_preload_history("tls", "comss.one", 17, 0, 1)
slm_preload_history("tls", "comss.one", 18, 0, 1)
slm_preload_history("tls", "comss.one", 19, 0, 1)
slm_preload_history("tls", "comss.one", 20, 0, 1)
slm_preload_history("tls", "comss.one", 21, 0, 1)
slm_preload_history("tls", "comss.one", 22, 0, 1)
slm_preload_history("tls", "comss.one", 23, 0, 1)
slm_preload_history("tls", "comss.one", 24, 0, 1)
slm_preload_history("tls", "comss.one", 25, 0, 1)
slm_preload_history("tls", "comss.one", 26, 0, 1)
slm_preload_history("tls", "comss.one", 27, 0, 1)
slm_preload_history("tls", "comss.one", 28, 0, 1)
slm_preload_history("tls", "comss.one", 29, 0, 1)
slm_preload_history("tls", "comss.one", 30, 7, 5)
slm_preload_history("tls", "comss.one", 31, 1, 1)
slm_preload_history("tls", "comss.one", 32, 0, 1)
slm_preload_history("tls", "comss.one", 33, 2, 1)
slm_preload_history("tls", "comss.one", 34, 2, 1)
slm_preload_history("tls", "comss.one", 35, 1, 1)
slm_preload_history("tls", "comss.one", 36, 0, 1)
slm_preload_history("tls", "comss.one", 37, 0, 1)
slm_preload_history("tls", "comss.one", 38, 0, 1)
slm_preload_history("tls", "comss.one", 39, 0, 1)
slm_preload_history("tls", "comss.one", 40, 0, 1)
slm_preload_history("tls", "comss.one", 41, 0, 1)
slm_preload_history("tls", "comss.one", 42, 0, 1)
slm_preload_history("tls", "comss.one", 43, 0, 1)
slm_preload_history("tls", "comss.one", 44, 0, 1)
slm_preload_history("tls", "comss.one", 45, 0, 1)
slm_preload_history("tls", "comss.one", 46, 0, 1)
slm_preload_history("tls", "comss.one", 47, 0, 1)
slm_preload_history("tls", "comss.one", 48, 0, 1)
slm_preload_history("tls", "comss.one", 49, 0, 1)
slm_preload_history("tls", "comss.one", 50, 0, 1)
slm_preload_history("tls", "comss.one", 51, 0, 1)
slm_preload_history("tls", "comss.one", 52, 0, 1)
slm_preload_history("tls", "comss.one", 53, 0, 1)
slm_preload_history("tls", "comss.one", 54, 0, 1)
slm_preload_history("tls", "comss.one", 55, 0, 1)
slm_preload_history("tls", "comss.one", 56, 0, 1)
slm_preload_history("tls", "comss.one", 57, 0, 1)
slm_preload_history("tls", "comss.one", 58, 0, 1)
slm_preload_history("tls", "comss.one", 59, 0, 1)
slm_preload_history("tls", "comss.one", 60, 0, 1)
slm_preload_history("tls", "comss.one", 61, 0, 1)
slm_preload_history("tls", "comss.one", 62, 0, 1)
slm_preload_history("tls", "comss.one", 63, 0, 1)
slm_preload_history("tls", "comss.one", 64, 0, 1)
slm_preload_history("tls", "comss.one", 65, 0, 1)
slm_preload_history("tls", "comss.one", 66, 10, 3)
slm_preload_history("tls", "comss.one", 67, 2, 1)
slm_preload_history("tls", "comss.one", 68, 1, 1)
slm_preload_history("tls", "vscode-cdn.net", 1, 4, 0)
slm_preload_history("tls", "visualstudio.com", 1, 1, 1)
slm_preload_history("tls", "visualstudio.com", 2, 1, 1)
slm_preload_history("tls", "visualstudio.com", 3, 10, 0)
slm_preload_history("tls", "vscode-unpkg.net", 1, 1, 0)
slm_preload_history("tls", "vsassets.io", 1, 10, 1)
slm_preload_history("tls", "vsassets.io", 2, 0, 1)
slm_preload_history("tls", "vsassets.io", 3, 2, 0)

DLOG("learned-strategies: loaded 58 strategies + 153 history (blocked: 0)")

-- Install circular wrapper to apply preloaded strategies on first packet
install_circular_wrapper()
DLOG("learned-strategies: wrapper installed, circular=" .. tostring(circular ~= nil) .. ", original=" .. tostring(original_circular ~= nil))

-- DEBUG: extra wrapper to diagnose APPLIED issue
if circular and working_strategies then
    local _debug_circular = circular
    circular = function(ctx, desync)
        local hostname = standard_hostkey and standard_hostkey(desync) or "?"
        local askey = (desync and desync.arg and desync.arg.key and #desync.arg.key>0) and desync.arg.key or (desync and desync.func_instance or "?")
        local data = working_strategies[hostname]
        if data then
            local expected = get_autostate_key_by_payload and get_autostate_key_by_payload(data.payload_type) or "?"
            DLOG("DEBUG circular: host=" .. hostname .. " askey=" .. askey .. " expected=" .. expected .. " locked=" .. tostring(data.locked) .. " applied=" .. tostring(data.applied))
        end
        return _debug_circular(ctx, desync)
    end
    DLOG("learned-strategies: DEBUG wrapper installed")
end

-- Install blocked strategies filter for circular rotation
-- slm_is_blocked() is defined in strategy-lock-manager.lua
local _blocked_wrap_installed = false
local function install_blocked_filter()
    if _blocked_wrap_installed then return end
    _blocked_wrap_installed = true
    if circular and type(circular) == "function" then
        local original_circular = circular
        circular = function(t, hostname, ...)
            local result = original_circular(t, hostname, ...)
            if result and hostname and slm_is_blocked(hostname, result) then
                local max_skip = 10
                for i = 1, max_skip do
                    result = original_circular(t, hostname, ...)
                    if not result or not slm_is_blocked(hostname, result) then break end
                    DLOG("BLOCKED: skip strategy " .. result .. " for " .. hostname)
                end
            end
            return result
        end
        DLOG("Blocked strategies filter installed for circular")
    end
end
install_blocked_filter()
