"""Regression test: ucode source comments must be C-style, not Lua-style.

The zapret2-orchestra runtime manager sources (apply.uc, generate-preload.uc)
were originally written with Lua-style ``--`` line comments, which the target
ucode treats as the decrement operator and refuses to parse (confirmed on the
router: ucode-2026.01.16 errors on ``-- comment`` but accepts ``// comment``).
The fix rewrote all real source comments to ``//`` while preserving ``--`` that
appears *inside string literals* (NFQWS2 flags like ``'--force'``, ``'--gen'``,
and the auto-generated Lua headers ``'-- Auto-generated ...'``).

This test guards against regressions on both sides:

* No Lua-style source comments remain in any shipped ``.uc`` file (the lexer
  in ``tests/_ucode_comment_lint.py`` distinguishes comment-position ``--`` from
  in-string ``--`` by tracking single/double quote state with escapes).
* The preserved in-string ``--`` sequences are still present (so a future
  over-eager conversion cannot silently delete the NFQWS2 flags or the Lua
  header that the preload generator emits).

It also spot-checks that the specific NFQWS2 flags and the Lua auto-generated
header strings survived the conversion byte-for-byte.
"""

from __future__ import annotations

import unittest
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
import _ucode_comment_lint as L  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
ORCH = ROOT / "openwrt" / "zapret2-orchestra" / "files"

# Every shipped ucode source that the runtime parses/compiles. The rpcd backend
# (no .uc extension) is included because ucode parses it too.
UCODE_SOURCES = [
    ORCH / "usr/share/zapret2-orchestra/apply.uc",
    ORCH / "usr/share/zapret2-orchestra/generate-preload.uc",
    ORCH / "usr/share/rpcd/ucode/zapret2.orchestra",
]


class UcodeCommentStyleTest(unittest.TestCase):
    """No Lua-style source comments may remain in shipped ucode sources."""

    def test_all_ucode_sources_have_no_lua_style_comments(self) -> None:
        for src in UCODE_SOURCES:
            with self.subTest(src=src.name):
                self.assertTrue(src.exists(), f"missing ucode source: {src}")
                text = src.read_text(encoding="utf-8")
                comments, string_dashes = L.scan_source(text)
                self.assertEqual(
                    comments, [],
                    f"{src.name} still has {len(comments)} Lua-style '--' source "
                    f"comments (first at line {comments[0].line}): "
                    f"{comments[0].full_line.strip()!r}" if comments else "",
                )

    def test_preserved_string_dashes_in_apply_uc(self) -> None:
        """NFQWS2 flags and error-message '--' inside string literals survive."""
        text = (ORCH / "usr/share/zapret2-orchestra/apply.uc").read_text(encoding="utf-8")
        _comments, string_dashes = L.scan_source(text)
        # The router-blocking conversion must not touch in-string '--'.
        self.assertGreaterEqual(len(string_dashes), 4,
                                "expected at least the --force/--gen string literals to be preserved")
        # Spot-check the exact NFQWS2 flag strings are still present byte-for-byte.
        self.assertIn("'--force'", text)
        self.assertIn("'--gen'", text)
        self.assertIn("use rollback with --force or re-apply a safe profile", text)
        # The comment that documents --lua-desync / --filter is a comment, so it
        # is now '// ... --lua-desync / --filter' — the flag text survives inside
        # the (now C-style) comment body.
        self.assertIn("--lua-desync / --filter", text)

    def test_preserved_lua_header_strings_in_generate_preload_uc(self) -> None:
        """The auto-generated Lua header '-- Auto-generated ...' is a string
        literal that becomes a Lua comment in the generated preload.lua; it must
        keep '--' (not be converted to '//')."""
        text = (ORCH / "usr/share/zapret2-orchestra/generate-preload.uc").read_text(encoding="utf-8")
        _comments, string_dashes = L.scan_source(text)
        self.assertGreaterEqual(len(string_dashes), 2,
                                "expected the Lua header string literals to be preserved")
        self.assertIn("'-- Auto-generated by zapret2-orchestra preload generator. Do not edit.',", text)
        self.assertIn("'-- Source: ' + STATE_DIR + '/*.json',", text)

    def test_rpcd_backend_has_no_lua_comments_and_was_not_converted(self) -> None:
        """The rpcd backend never used Lua-style comments; assert it is clean
        and that its (valid) imports are untouched."""
        text = (ORCH / "usr/share/rpcd/ucode/zapret2.orchestra").read_text(encoding="utf-8")
        comments, _string_dashes = L.scan_source(text)
        self.assertEqual(comments, [], "rpcd backend should have no Lua-style comments")

    def test_converter_is_idempotent_on_already_clean_sources(self) -> None:
        """Running the converter again on the fixed sources is a no-op: no
        comments to convert, and the same set of string dashes is preserved."""
        for src in UCODE_SOURCES:
            with self.subTest(src=src.name):
                text = src.read_text(encoding="utf-8")
                converted = L.convert_source(text)
                _c_before, s_before = L.scan_source(text)
                _c_after, s_after = L.scan_source(converted)
                self.assertEqual(s_before, s_after,
                                 f"converter changed preserved string dashes in {src.name}")


class UcodeCommentLexerUnitTest(unittest.TestCase):
    """Unit tests for the lexer that the converter and the test above share.
    These pin the exact semantics of 'comment vs string-dash' so a future
    refactor of the lexer cannot silently regress the distinction."""

    def test_pure_lua_comment_is_detected(self) -> None:
        comments, _ = L.scan_source("-- hello\nprint('x')\n")
        self.assertEqual(len(comments), 1)
        self.assertEqual(comments[0].line, 1)
        self.assertEqual(comments[0].column, 0)

    def test_indented_lua_comment_is_detected(self) -> None:
        comments, _ = L.scan_source("\t// ok\n    -- bad\n")
        self.assertEqual(len(comments), 1)
        self.assertEqual(comments[0].line, 2)

    def test_dashdash_inside_single_quoted_string_is_preserved(self) -> None:
        # The NFQWS2 flag '--force' is a string literal, not a comment.
        _comments, strings = L.scan_source("if (ARGV[i] == '--force') force = true;\n")
        self.assertEqual(len(strings), 1)
        self.assertEqual(strings[0].line, 1)

    def test_dashdash_inside_double_quoted_string_is_preserved(self) -> None:
        _comments, strings = L.scan_source('let s = "a--b";\n')
        self.assertEqual(len(strings), 1)

    def test_escaped_quote_does_not_terminate_string(self) -> None:
        # 'it\'s --force' — the escaped quote keeps the string open so the
        # '--force' inside is a preserved string-dash, not a comment.
        _comments, strings = L.scan_source("let s = 'it\\'s --force';\n")
        self.assertEqual(len(strings), 1)
        comments2, _ = L.scan_source("let s = 'it\\'s ok'; -- trailing bad\n")
        self.assertEqual(len(comments2), 1)
        self.assertEqual(comments2[0].column, 20)

    def test_c_style_comment_terminates_line_scan(self) -> None:
        # A C-style comment ends the scan; any '--' after it is comment body,
        # not a new Lua comment.
        comments, _ = L.scan_source("// hello -- world\n")
        self.assertEqual(comments, [])

    def test_inline_comment_after_code(self) -> None:
        # code -- comment  →  the '--' starts a Lua comment at that column
        comments, _ = L.scan_source("let x = 1 -- inline bad\n")
        self.assertEqual(len(comments), 1)
        self.assertEqual(comments[0].column, 10)

    def test_convert_line_rewrites_only_first_lua_comment(self) -> None:
        self.assertEqual(L.convert_line("-- bad"), "// bad")
        self.assertEqual(L.convert_line("\t-- bad"), "\t// bad")
        # string-dash line is unchanged
        self.assertEqual(L.convert_line("if (x == '--force') y;"),
                         "if (x == '--force') y;")
        # C-style comment line is unchanged
        self.assertEqual(L.convert_line("// already good"), "// already good")
        # code + inline lua comment
        self.assertEqual(L.convert_line("let x = 1 -- bad"),
                         "let x = 1 // bad")


if __name__ == "__main__":
    unittest.main()
