-- Auto-generated by zapret2-orchestra preload generator. Do not edit.
-- Source: /etc/zapret2-orchestra/*.json
ORCHESTRA_WHITELIST = { ["a.example"]=true, ["b.example"]=true }
slm_preload_blocked("tls", "*", {1, 3})
slm_preload_blocked("tls", "video.example", {2})
slm_preload_history("tls", "host10.example", 1, 5, 2)
slm_preload_history("tls", "host10.example", 10, 1, 0)
slm_preload_history("tls", "host10.example", 2, 0, 1)
slm_preload_history("tls", "video.example", 2, 3, 1)
slm_preload_locked("tls", "video.example", 2, false)
slm_preload_locked("tls", "manual.example", 2, true)
